spring.application.name=api-gateway
server.port=${PORT:8080}
app.cors.allowed-origin-patterns=${CORS_ALLOWED_ORIGIN_PATTERNS:http://localhost:5173,https://*.vercel.app}

auth.jwt.secret=${AUTH_JWT_SECRET:QWJjZEVmZ0hpSmtMbW5PcFFyU3RVdld4WXpBQkNERUZHSElKS0xtbm9w}


spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=${AUTH_SERVICE_URI:lb://auth-service}
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**
spring.cloud.gateway.routes[0].filters[0]=RewritePath=/auth/(?<segment>.*), /api/auth/$\{segment}

spring.cloud.gateway.routes[1].id=post-category-tag-service
spring.cloud.gateway.routes[1].uri=${POST_CATEGORY_TAG_SERVICE_URI:lb://post-category-tag-service}
spring.cloud.gateway.routes[1].predicates[0]=Path=/posts/**,/categories/**,/tags/**,/admin/**
spring.cloud.gateway.routes[1].filters[0]=RewritePath=/(?<segment>.*), /api/$\{segment}

spring.cloud.gateway.routes[2].id=comment-like-service
spring.cloud.gateway.routes[2].uri=${COMMENT_LIKE_SERVICE_URI:lb://comment-like-service}
spring.cloud.gateway.routes[2].predicates[0]=Path=/comments/**
spring.cloud.gateway.routes[2].filters[0]=RewritePath=/comments(?<segment>/?.*), /api/comments$\{segment}

spring.cloud.gateway.routes[3].id=media-service
spring.cloud.gateway.routes[3].uri=${MEDIA_SERVICE_URI:lb://media-service}
spring.cloud.gateway.routes[3].predicates[0]=Path=/media/**
spring.cloud.gateway.routes[3].filters[0]=RewritePath=/media(?<segment>/?.*), /api/media$\{segment}

spring.cloud.gateway.routes[4].id=newsletter-subscription-service
spring.cloud.gateway.routes[4].uri=${NEWSLETTER_SERVICE_URI:lb://newsletter-subscription-service}
spring.cloud.gateway.routes[4].predicates[0]=Path=/newsletter/**
spring.cloud.gateway.routes[4].filters[0]=RewritePath=/newsletter/(?<segment>.*), /api/newsletter/$\{segment}

spring.cloud.gateway.routes[5].id=notification-service
spring.cloud.gateway.routes[5].uri=${NOTIFICATION_SERVICE_URI:lb://notification-service}
spring.cloud.gateway.routes[5].predicates[0]=Path=/notifications/**
spring.cloud.gateway.routes[5].filters[0]=RewritePath=/notifications/(?<segment>.*), /api/notifications/$\{segment}

spring.cloud.gateway.routes[6].id=auth-oauth-bridge
spring.cloud.gateway.routes[6].uri=${AUTH_SERVICE_URI:lb://auth-service}
spring.cloud.gateway.routes[6].predicates[0]=Path=/oauth2/**,/login/**


eureka.client.enabled=${EUREKA_ENABLED:true}
eureka.client.service-url.defaultZone=${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka}
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}:${random.value}

