spring.application.name=post-category-tag-service
server.port=${PORT:8082}

spring.datasource.url=${DB_URL:jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/scriptly_posts?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:password}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=${JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=true

services.newsletter.base-url=${NEWSLETTER_SERVICE_BASE_URL:http://localhost:8085}
services.comment.base-url=${COMMENT_SERVICE_BASE_URL:http://localhost:8083}
services.auth.base-url=${AUTH_SERVICE_BASE_URL:http://localhost:8081}
services.notification.base-url=${NOTIFICATION_SERVICE_BASE_URL:http://localhost:8086}



spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USER:guest}
spring.rabbitmq.password=${RABBITMQ_PASS:guest}

spring.cache.type=redis
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

eureka.client.enabled=${EUREKA_ENABLED:true}
eureka.client.service-url.defaultZone=${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka}
eureka.instance.prefer-ip-address=false
eureka.instance.hostname=${EUREKA_INSTANCE_HOSTNAME:localhost}

